name: deploy blogs
on: [push]
jobs:
  deploy-hugo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: hugo
        uses: klakegg/actions-hugo@1.0.0
