name: deploy blogs
on:
  push:
    branches:
      - master

jobs:
  deploy-hugo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          ref: master
          path: source

      - name: Install hugo
        run: |
          cd ~
          wget https://github.com/gohugoio/hugo/releases/download/v0.83.1/hugo_extended_0.83.1_Linux-64bit.tar.gz
          tar zxvf hugo_extended_0.83.1_Linux-64bit.tar.gz

      - name: Build site
        run: cd /home/runner/work/blog-source/blog-source/source && ~/hugo --minify

      - name: Checkout blog page content
        uses: actions/checkout@v2
        with:
          repository: blackdiz/blackdiz.github.io
          path: blog
          token: ${{ secrets.ACCESS_SECRET_FOR_ACCESS_BLOG_PAGE }}

      - name: Copy new blog contents, commit, then push
        run: |
          cd /home/runner/work/blog-source/blog-source/blog
          rm -rf ./*
          cp -a /home/runner/work/blog-source/blog-source/source/public/. .
          echo $(date) > .update-date
          git add .
          git commit -m "Update blog"
          git push

      - name: Send an event to trigger the action to update blog posts list in my Github profile
        run: |
          curl -X POST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/blackdiz/blackdiz/dispatches --data '{"ref": "master"}'
