name: deploy blogs
on: [push]
jobs:
  deploy-hugo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2.1.3
      - run: sudo apt-get install hugo
      - run: hugo -D

