name: deploy blogs
on: [push]
jobs:
  deploy-hugo:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
          ref: 'draft'

      - name: Install hugo
        run: brew install hugo

      - name: Build site
        run: hugo -D
